---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: inspire-qa
  name: json-benchmark
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2G
  storageClassName: meyrin-cephfs

---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: inspire-qa
  name: json-benchmark
  labels:
    app.kubernetes.io/name: json-benchmark
spec:
  completions: 10
  template:
    metadata:
      labels:
        app.kubernetes.io/name: json-benchmark
    spec:
      volumes:
        - name: json-benchmark
          persistentVolumeClaim:
            claimName: json-benchmark
      containers:
        - image: inspirehep/json-benchmark
          name: json-benchmark
          resources:
            requests:
              memory: 1Gi
            limits:
              memory: 3Gi
          volumeMounts:
            - name: json-benchmark
              mountPath: /data
          workingDir: /
          command: ["python3"]
          args: ["/opt/src/tests.py"]
      restartPolicy: Never

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: inspire-qa
  name: json-benchmark-idler
  labels:
    app.kubernetes.io/name: json-benchmark-idler
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: json-benchmark-idler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: json-benchmark-idler
    spec:
      volumes:
        - name: json-benchmark
          persistentVolumeClaim:
            claimName: json-benchmark
      containers:
        - image: inspirehep/json-benchmark
          name: idler
          command: ['bash']
          args: ['-c', 'while sleep 3600; do :; done']
          resources:
            requests:
              memory: 1Gi
            limits:
              memory: 3Gi
          volumeMounts:
            - name: json-benchmark
              mountPath: /data
